# zuul-gateway-local.yml
spring:
  profiles: local
zuul:
  routes:
    member:
      stripPrefix: false
      path: /v1/member/**
      url: http://localhost:8080
    pay:
      stripPrefix: false
      path: /v1/pay/**
      url: http://localhost:8080
    else:
      stripPrefix: false
      path: /v1/**
      url: http://localhost:8081
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true